#!/usr/bin/env python3
"""Capture NetEase Cloud Music login cookies for yt-dlp.

Opens Chrome to music.163.com, waits for manual login,
then saves cookies in Netscape format and exits.
"""

import argparse
import sys
import time
from pathlib import Path

from playwright.sync_api import sync_playwright


NETEASE_URL = "https://music.163.com/"
COOKIE_CHECK = "MUSIC_U"          # primary session cookie set after login
POLL_INTERVAL = 2                  # seconds between cookie checks
TIMEOUT = 600                      # max wait (10 minutes)


def login_detected(context) -> bool:
    """Return True when NetEase login cookies are present."""
    cookies = context.cookies()
    return any(c["name"] == COOKIE_CHECK and c["value"] for c in cookies)


def save_netscape(cookies, path: Path):
    """Save cookies in Netscape format (compatible with yt-dlp --cookies)."""
    path.parent.mkdir(parents=True, exist_ok=True)
    domain = ".music.163.com"
    with open(path, "w") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by netease-cookies helper\n\n")
        for c in cookies:
            if domain not in c.get("domain", ""):
                continue
            domain_flag = "TRUE" if c["domain"].startswith(".") else "FALSE"
            secure = "TRUE" if c.get("secure", False) else "FALSE"
            expires = str(int(c.get("expires", -1))) if c.get("expires", -1) > 0 else "0"
            f.write(
                "\t".join([
                    c["domain"],
                    domain_flag,
                    str(c["path"]),
                    secure,
                    expires,
                    c["name"],
                    c["value"],
                ])
                + "\n"
            )


def main():
    parser = argparse.ArgumentParser(
        description="Capture NetEase Cloud Music login cookies"
    )
    parser.add_argument(
        "-o", "--output",
        default=str(Path.home() / ".netease-radio" / "cookies.txt"),
        help="Output cookies.txt path (default: ~/.netease-radio/cookies.txt)",
    )
    args = parser.parse_args()
    output = Path(args.output)

    print(f"Opening Chrome to {NETEASE_URL}")
    print("Please log in to your NetEase Cloud Music account...")
    print(f"Waiting up to {TIMEOUT} seconds (Ctrl-C to cancel)\n")

    with sync_playwright() as p:
        browser = p.chromium.launch(
            headless=False,
            channel="chrome",
            args=["--disable-blink-features=AutomationControlled"],
        )
        context = browser.new_context(
            viewport={"width": 1280, "height": 800},
        )
        page = context.new_page()
        page.goto(NETEASE_URL, wait_until="domcontentloaded")

        elapsed = 0
        while not login_detected(context):
            time.sleep(POLL_INTERVAL)
            elapsed += POLL_INTERVAL
            if elapsed >= TIMEOUT:
                print("Login timeout – no MUSIC_U cookie detected.")
                browser.close()
                sys.exit(1)

        print("Login detected. Saving cookies...")
        cookies = context.cookies()
        save_netscape(cookies, output)

        browser.close()

    print(f"Cookies saved to {output}")
    print(
        "Add this to your Emacs config:"
        f"\n  (setq netease-radio-yt-dlp-cookies \"{output}\")"
    )


if __name__ == "__main__":
    main()
